/* Palette generated by Material Palette - materialpalette.com/cyan/amber */
export const primaryColorDark = '#0097A7';
export const primaryColor = '#00BCD4';
export const primaryColorLight = '#B2EBF2';
export const primaryColorText = '#FFFFFF';
export const accentColor = '#FFC107';
export const primaryTextColor = '#212121';
export const secondaryTextColor = '#757575';
export const dividerColor = '#BDBDBD';
